FROM debian:jessie

# install all build dependencies
RUN apt-get update && \
    apt-get install -y openjdk-7-jre build-essential libevent-dev libssl-dev make git gcc curl && \
    rm -rf /var/lib/apt/lists/*

# the cmake that debian stable is shipping is too old (we need minimium 2.8.9)
RUN curl -O http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz && \
    tar -xf cmake-3.3.1-Linux-x86_64.tar.gz && \
    mv cmake-3.3.1-Linux-x86_64/bin/* /usr/bin && \
    mv cmake-3.3.1-Linux-x86_64/share/cmake-3.3 /usr/share

RUN git clone git://github.com/mnunberg/libcouchbase.git -b perf-external

RUN mkdir -p libcouchbase/build
RUN cd libcouchbase/build && ../cmake/configure && make && ctest

# fetch and build wrk
RUN cd / && git clone https://github.com/wg/wrk.git && \
    cd /wrk && \
    make
