FROM gliderlabs/alpine:3.2

RUN apk update && apk add bash curl git mercurial bzr go make && rm -rf /var/cache/apk/*

ENV GOROOT /usr/lib/go
ENV GOPATH /gopath
ENV GOBIN /gopath/bin
ENV PATH $PATH:$GOROOT/bin:$GOPATH/bin
