#!/bin/bash

# usage:
# ./poll-stats parameters-of-test
# example:
# ./poll-stats cb4-nodes3-XXgb-docs1m-pf3-threads10
# outputs:
# ./stats/parameters-of-test-2015:09:18-10:11:20.json

NAME=$1

while true
do
    DATE=$(date "+%Y:%m:%d-%H:%M:%SZ")
    mkdir -p ./stats

    echo polling stats at ${DATE}...
    curl -so ./stats/${NAME}-cluster-${DATE}.json "http://Administrator:password@165.225.157.162:8091/pools/default"
    curl -so ./stats/${NAME}-stats-${DATE}.json "http://Administrator:password@165.225.157.162:8091/pools/default/overviewStats"

    echo pushing up to manta...
    mput -a timgross -f ./stats/${NAME}-cluster-${DATE}.json /timgross/public
    mput -a timgross -f ./stats/${NAME}-stats-${DATE}.json /timgross/public

    sleep 30
done
